### ISSUE TITLE
The editor is not loading when creating a new event in the calendar

### ISSUE THREAD

**Issue by acotiuga** [xwikisas/application-mocca-calendar#7]
![editornotloading](https://user-images.githubusercontent.com/8121819/37032743-3f2052d8-214c-11e8-9526-72b463514ef6.png)

**Comment by ane-gabriela** [comment]
Linked to https://jira.xwiki.org/browse/MOCCACAL-111 which was fixed.

**Comment by lucaa** [comment]
Reopening, as the fix for MOCCACAL-111 was imprecisely applied and the issue still reproduces.

As far as I can understand, the fix for MOCCACAL-111 was to change the MoccaCalendarEventClass (which holds the events of the calendar) while the fix applied for this issue is changing MoccaCalendarClass (which holds the definition of a calendar) .

**Comment by mflorea** [comment]
@acotiuga please use ``cherry-pick -x`` to take commits from contrib, otherwise:

* you can easily do mistakes, like in this case
* you don't give credits to the real commit author, which is not fair

**Comment by acotiuga** [comment]
Fixed in e199baf0b85d387f3e1171ce4d608b9ffa0b6321. Sorry for the mistake and thanks for guidance.
